
AllCops:
  TargetRubyVersion: 2.3

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MethodName:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ParameterLists:
  Max: 10
